#!/usr/bin/env bash
# Template generation for Vulnotes CLI

TEMPLATES_DIR="$SCRIPT_DIR/templates"

generate_docker_compose() {
    local http_port="${1:-80}"
    local bind_address="${2:-127.0.0.1}"

    sed -e "s|{{HTTP_PORT}}|${http_port}|g" \
        -e "s|{{BIND_ADDRESS}}|${bind_address}|g" \
        "$TEMPLATES_DIR/docker-compose.yml.tmpl" > "$COMPOSE_FILE"
}

generate_nginx_conf() {
    cp "$TEMPLATES_DIR/nginx.conf.tmpl" "$INSTALL_DIR/nginx.conf"
}

generate_env_file() {
    local domain="$1"
    local jwt_secret="$2"
    local backronaut_secret="$3"

    cat > "$ENV_FILE" << ENV_EOF
# Vulnotes Environment Configuration
# Generated by vulnotes-cli

DOMAIN=${domain}
JWT_SECRET=${jwt_secret}
BACKRONAUT_SECRET=${backronaut_secret}
ENV_EOF

    chmod 600 "$ENV_FILE"
}
