#!/usr/bin/env bash
# Template generation for Vulnotes CLI

TEMPLATES_DIR="$SCRIPT_DIR/templates"

generate_docker_compose() {
    local http_port="${1:-80}"
    local bind_address="${2:-127.0.0.1}"

    sed -e "s|{{HTTP_PORT}}|${http_port}|g" \
        -e "s|{{BIND_ADDRESS}}|${bind_address}|g" \
        "$TEMPLATES_DIR/docker-compose.yml.tmpl" > "$COMPOSE_FILE"
}

generate_nginx_conf() {
    cp "$TEMPLATES_DIR/nginx.conf.tmpl" "$INSTALL_DIR/nginx.conf"
}

generate_env_file() {
    local domain="$1"
    local jwt_secret="$2"
    local backronaut_secret="$3"
    local support_api_token="$4"
    local http_port="${5:-80}"
    local puppeteer_service_token="${6:-}"
    [[ -n "$puppeteer_service_token" ]] || puppeteer_service_token=$(generate_random_hex 32)

    if ! [[ "$puppeteer_service_token" =~ ^[0-9a-f]{64}$ ]]; then
        log_error "Refusing to write an invalid renderer service token"
        return 1
    fi

    # Compose DOMAIN with port so it matches the browser-sent Origin header.
    # Skip if the domain already includes a port, or if the port is the
    # scheme's default (80 for http, 443 for https).
    local domain_with_port="$domain"
    if [[ ! "$domain" =~ ^[a-zA-Z]+://[^/]+:[0-9]+ ]]; then
        local default_port=80
        [[ "$domain" =~ ^https:// ]] && default_port=443
        if [[ "$http_port" != "$default_port" ]]; then
            domain_with_port="${domain}:${http_port}"
        fi
    fi

    local env_dir env_tmp
    env_dir=$(dirname "$ENV_FILE")
    env_tmp=$(mktemp "$env_dir/.env.tmp.XXXXXX") || return 1
    chmod 600 "$env_tmp" || { rm -f "$env_tmp"; return 1; }

    if ! cat > "$env_tmp" << ENV_EOF
# Vulnotes Environment Configuration
# Generated by vulnotes-cli

DOMAIN=${domain_with_port}
JWT_SECRET=${jwt_secret}
BACKRONAUT_SECRET=${backronaut_secret}
SUPPORT_API_TOKEN=${support_api_token}
PUPPETEER_SERVICE_TOKEN=${puppeteer_service_token}
ENV_EOF
    then
        rm -f "$env_tmp"
        return 1
    fi

    mv -f "$env_tmp" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
}

# Validate the baseline before migrating an older installation. An update must
# never turn an absent or damaged .env into a token-only configuration.
validate_update_env_file() {
    if [[ ! -f "$ENV_FILE" || -L "$ENV_FILE" ]]; then
        log_error "Missing or unsafe $ENV_FILE; repair it before updating"
        return 1
    fi

    local required key count
    for required in DOMAIN JWT_SECRET; do
        count=$(grep -Ec "^${required}=" "$ENV_FILE" || true)
        if [[ "$count" -ne 1 ]]; then
            log_error "$ENV_FILE must contain exactly one ${required}= entry"
            return 1
        fi
        key=$(sed -n "s/^${required}=//p" "$ENV_FILE")
        if [[ -z "$key" ]]; then
            log_error "$ENV_FILE contains an empty ${required} value"
            return 1
        fi
    done

    count=$(grep -Ec '^PUPPETEER_SERVICE_TOKEN=' "$ENV_FILE" || true)
    if [[ "$count" -gt 1 ]]; then
        log_error "$ENV_FILE contains duplicate PUPPETEER_SERVICE_TOKEN entries"
        return 1
    fi
}

# Atomically installs a fresh token when missing/invalid and always repairs the
# permissions of an existing valid file. The token is intentionally independent
# from JWT_SECRET so compromise of one credential does not reveal the other.
ensure_renderer_secret() {
    validate_update_env_file || return 1

    local current="" token env_tmp
    current=$(sed -n 's/^PUPPETEER_SERVICE_TOKEN=//p' "$ENV_FILE")
    if [[ "$current" =~ ^[0-9a-f]{64}$ ]]; then
        chmod 600 "$ENV_FILE" || return 1
        return 0
    fi

    token=$(generate_random_hex 32)
    [[ "$token" =~ ^[0-9a-f]{64}$ ]] || return 1
    env_tmp=$(mktemp "$(dirname "$ENV_FILE")/.env.renderer.XXXXXX") || return 1
    chmod 600 "$env_tmp" || { rm -f "$env_tmp"; return 1; }

    if grep -q '^PUPPETEER_SERVICE_TOKEN=' "$ENV_FILE"; then
        awk -v token="$token" '
            /^PUPPETEER_SERVICE_TOKEN=/ { print "PUPPETEER_SERVICE_TOKEN=" token; next }
            { print }
        ' "$ENV_FILE" > "$env_tmp"
    else
        {
            cat "$ENV_FILE"
            printf '\nPUPPETEER_SERVICE_TOKEN=%s\n' "$token"
        } > "$env_tmp"
    fi

    if ! mv -f "$env_tmp" "$ENV_FILE"; then
        rm -f "$env_tmp"
        return 1
    fi
    chmod 600 "$ENV_FILE" || return 1
    log_success "Configured secure internal document renderer credentials"
}
